/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as RequirementsIndexRouteImport } from './routes/requirements/index'
import { Route as OIndexRouteImport } from './routes/o/index'
import { Route as WorkflowsSplatRouteImport } from './routes/workflows/$'
import { Route as TasksSplatRouteImport } from './routes/tasks/$'
import { Route as SettingsPreferencesRouteImport } from './routes/settings/preferences'
import { Route as SettingsPasswordRouteImport } from './routes/settings/password'
import { Route as RequirementsSplatRouteImport } from './routes/requirements/$'
import { Route as OSplatRouteImport } from './routes/o/$'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoErrorDisplayRouteImport } from './routes/demo/error-display'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsIndexRoute = RequirementsIndexRouteImport.update({
  id: '/requirements/',
  path: '/requirements/',
  getParentRoute: () => rootRouteImport,
} as any)
const OIndexRoute = OIndexRouteImport.update({
  id: '/o/',
  path: '/o/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsSplatRoute = WorkflowsSplatRouteImport.update({
  id: '/workflows/$',
  path: '/workflows/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSplatRoute = TasksSplatRouteImport.update({
  id: '/tasks/$',
  path: '/tasks/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPasswordRoute = SettingsPasswordRouteImport.update({
  id: '/settings/password',
  path: '/settings/password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsSplatRoute = RequirementsSplatRouteImport.update({
  id: '/requirements/$',
  path: '/requirements/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OSplatRoute = OSplatRouteImport.update({
  id: '/o/$',
  path: '/o/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoErrorDisplayRoute = DemoErrorDisplayRouteImport.update({
  id: '/demo/error-display',
  path: '/demo/error-display',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
  '/api/chat': typeof ApiChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/error-display': typeof DemoErrorDisplayRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/o/$': typeof OSplatRoute
  '/requirements/$': typeof RequirementsSplatRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/tasks/$': typeof TasksSplatRoute
  '/workflows/$': typeof WorkflowsSplatRoute
  '/o/': typeof OIndexRoute
  '/requirements/': typeof RequirementsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
  '/api/chat': typeof ApiChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/error-display': typeof DemoErrorDisplayRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/o/$': typeof OSplatRoute
  '/requirements/$': typeof RequirementsSplatRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/tasks/$': typeof TasksSplatRoute
  '/workflows/$': typeof WorkflowsSplatRoute
  '/o': typeof OIndexRoute
  '/requirements': typeof RequirementsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
  '/api/chat': typeof ApiChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/error-display': typeof DemoErrorDisplayRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/o/$': typeof OSplatRoute
  '/requirements/$': typeof RequirementsSplatRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/tasks/$': typeof TasksSplatRoute
  '/workflows/$': typeof WorkflowsSplatRoute
  '/o/': typeof OIndexRoute
  '/requirements/': typeof RequirementsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/logs'
    | '/usage'
    | '/users'
    | '/api/chat'
    | '/demo/better-auth'
    | '/demo/error-display'
    | '/demo/prisma'
    | '/o/$'
    | '/requirements/$'
    | '/settings/password'
    | '/settings/preferences'
    | '/tasks/$'
    | '/workflows/$'
    | '/o/'
    | '/requirements/'
    | '/tasks/'
    | '/workflows/'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/logs'
    | '/usage'
    | '/users'
    | '/api/chat'
    | '/demo/better-auth'
    | '/demo/error-display'
    | '/demo/prisma'
    | '/o/$'
    | '/requirements/$'
    | '/settings/password'
    | '/settings/preferences'
    | '/tasks/$'
    | '/workflows/$'
    | '/o'
    | '/requirements'
    | '/tasks'
    | '/workflows'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/logs'
    | '/usage'
    | '/users'
    | '/api/chat'
    | '/demo/better-auth'
    | '/demo/error-display'
    | '/demo/prisma'
    | '/o/$'
    | '/requirements/$'
    | '/settings/password'
    | '/settings/preferences'
    | '/tasks/$'
    | '/workflows/$'
    | '/o/'
    | '/requirements/'
    | '/tasks/'
    | '/workflows/'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  UsageRoute: typeof UsageRoute
  UsersRoute: typeof UsersRoute
  ApiChatRoute: typeof ApiChatRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoErrorDisplayRoute: typeof DemoErrorDisplayRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  OSplatRoute: typeof OSplatRoute
  RequirementsSplatRoute: typeof RequirementsSplatRoute
  SettingsPasswordRoute: typeof SettingsPasswordRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  TasksSplatRoute: typeof TasksSplatRoute
  WorkflowsSplatRoute: typeof WorkflowsSplatRoute
  OIndexRoute: typeof OIndexRoute
  RequirementsIndexRoute: typeof RequirementsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements/': {
      id: '/requirements/'
      path: '/requirements'
      fullPath: '/requirements/'
      preLoaderRoute: typeof RequirementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/': {
      id: '/o/'
      path: '/o'
      fullPath: '/o/'
      preLoaderRoute: typeof OIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$': {
      id: '/workflows/$'
      path: '/workflows/$'
      fullPath: '/workflows/$'
      preLoaderRoute: typeof WorkflowsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$': {
      id: '/tasks/$'
      path: '/tasks/$'
      fullPath: '/tasks/$'
      preLoaderRoute: typeof TasksSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/password': {
      id: '/settings/password'
      path: '/settings/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof SettingsPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements/$': {
      id: '/requirements/$'
      path: '/requirements/$'
      fullPath: '/requirements/$'
      preLoaderRoute: typeof RequirementsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$': {
      id: '/o/$'
      path: '/o/$'
      fullPath: '/o/$'
      preLoaderRoute: typeof OSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/error-display': {
      id: '/demo/error-display'
      path: '/demo/error-display'
      fullPath: '/demo/error-display'
      preLoaderRoute: typeof DemoErrorDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  UsageRoute: UsageRoute,
  UsersRoute: UsersRoute,
  ApiChatRoute: ApiChatRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoErrorDisplayRoute: DemoErrorDisplayRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  OSplatRoute: OSplatRoute,
  RequirementsSplatRoute: RequirementsSplatRoute,
  SettingsPasswordRoute: SettingsPasswordRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  TasksSplatRoute: TasksSplatRoute,
  WorkflowsSplatRoute: WorkflowsSplatRoute,
  OIndexRoute: OIndexRoute,
  RequirementsIndexRoute: RequirementsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
