/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatDebugRouteImport } from './routes/chat-debug'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as TriggersIndexRouteImport } from './routes/triggers/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RequirementsIndexRouteImport } from './routes/requirements/index'
import { Route as OIndexRouteImport } from './routes/o/index'
import { Route as WorkflowsSplatRouteImport } from './routes/workflows/$'
import { Route as TriggersSplatRouteImport } from './routes/triggers/$'
import { Route as TasksSplatRouteImport } from './routes/tasks/$'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPasswordRouteImport } from './routes/settings/password'
import { Route as SettingsObsidianRouteImport } from './routes/settings/obsidian'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsChatRouteImport } from './routes/settings/chat'
import { Route as SettingsCalendarRouteImport } from './routes/settings/calendar'
import { Route as RequirementsSplatRouteImport } from './routes/requirements/$'
import { Route as PPluginIdRouteImport } from './routes/p/$pluginId'
import { Route as OSplatRouteImport } from './routes/o/$'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoErrorDisplayRouteImport } from './routes/demo/error-display'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as WorkflowsEditorIndexRouteImport } from './routes/workflows/editor/index'
import { Route as TriggersEditorIndexRouteImport } from './routes/triggers/editor/index'
import { Route as TasksEditorIndexRouteImport } from './routes/tasks/editor/index'
import { Route as SettingsPluginsIndexRouteImport } from './routes/settings/plugins/index'
import { Route as WorkflowsEditorSplatRouteImport } from './routes/workflows/editor/$'
import { Route as TriggersEditorSplatRouteImport } from './routes/triggers/editor/$'
import { Route as TasksEditorSplatRouteImport } from './routes/tasks/editor/$'
import { Route as SettingsPluginsPluginIdRouteImport } from './routes/settings/plugins/$pluginId'
import { Route as PPluginIdPageIdRouteImport } from './routes/p/$pluginId/$pageId'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatDebugRoute = ChatDebugRouteImport.update({
  id: '/chat-debug',
  path: '/chat-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const TriggersIndexRoute = TriggersIndexRouteImport.update({
  id: '/triggers/',
  path: '/triggers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const RequirementsIndexRoute = RequirementsIndexRouteImport.update({
  id: '/requirements/',
  path: '/requirements/',
  getParentRoute: () => rootRouteImport,
} as any)
const OIndexRoute = OIndexRouteImport.update({
  id: '/o/',
  path: '/o/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsSplatRoute = WorkflowsSplatRouteImport.update({
  id: '/workflows/$',
  path: '/workflows/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TriggersSplatRoute = TriggersSplatRouteImport.update({
  id: '/triggers/$',
  path: '/triggers/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSplatRoute = TasksSplatRouteImport.update({
  id: '/tasks/$',
  path: '/tasks/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPasswordRoute = SettingsPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsObsidianRoute = SettingsObsidianRouteImport.update({
  id: '/obsidian',
  path: '/obsidian',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsChatRoute = SettingsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCalendarRoute = SettingsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const RequirementsSplatRoute = RequirementsSplatRouteImport.update({
  id: '/requirements/$',
  path: '/requirements/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PPluginIdRoute = PPluginIdRouteImport.update({
  id: '/p/$pluginId',
  path: '/p/$pluginId',
  getParentRoute: () => rootRouteImport,
} as any)
const OSplatRoute = OSplatRouteImport.update({
  id: '/o/$',
  path: '/o/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoErrorDisplayRoute = DemoErrorDisplayRouteImport.update({
  id: '/demo/error-display',
  path: '/demo/error-display',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsEditorIndexRoute = WorkflowsEditorIndexRouteImport.update({
  id: '/workflows/editor/',
  path: '/workflows/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const TriggersEditorIndexRoute = TriggersEditorIndexRouteImport.update({
  id: '/triggers/editor/',
  path: '/triggers/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksEditorIndexRoute = TasksEditorIndexRouteImport.update({
  id: '/tasks/editor/',
  path: '/tasks/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPluginsIndexRoute = SettingsPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const WorkflowsEditorSplatRoute = WorkflowsEditorSplatRouteImport.update({
  id: '/workflows/editor/$',
  path: '/workflows/editor/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TriggersEditorSplatRoute = TriggersEditorSplatRouteImport.update({
  id: '/triggers/editor/$',
  path: '/triggers/editor/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksEditorSplatRoute = TasksEditorSplatRouteImport.update({
  id: '/tasks/editor/$',
  path: '/tasks/editor/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPluginsPluginIdRoute = SettingsPluginsPluginIdRouteImport.update({
  id: '/plugins/$pluginId',
  path: '/plugins/$pluginId',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const PPluginIdPageIdRoute = PPluginIdPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => PPluginIdRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/chat': typeof ChatRoute
  '/chat-debug': typeof ChatDebugRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/notifications': typeof NotificationsRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
  '/api/chat': typeof ApiChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/error-display': typeof DemoErrorDisplayRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/o/$': typeof OSplatRoute
  '/p/$pluginId': typeof PPluginIdRouteWithChildren
  '/requirements/$': typeof RequirementsSplatRoute
  '/settings/calendar': typeof SettingsCalendarRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/obsidian': typeof SettingsObsidianRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tasks/$': typeof TasksSplatRoute
  '/triggers/$': typeof TriggersSplatRoute
  '/workflows/$': typeof WorkflowsSplatRoute
  '/o/': typeof OIndexRoute
  '/requirements/': typeof RequirementsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/triggers/': typeof TriggersIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/p/$pluginId/$pageId': typeof PPluginIdPageIdRoute
  '/settings/plugins/$pluginId': typeof SettingsPluginsPluginIdRoute
  '/tasks/editor/$': typeof TasksEditorSplatRoute
  '/triggers/editor/$': typeof TriggersEditorSplatRoute
  '/workflows/editor/$': typeof WorkflowsEditorSplatRoute
  '/settings/plugins/': typeof SettingsPluginsIndexRoute
  '/tasks/editor/': typeof TasksEditorIndexRoute
  '/triggers/editor/': typeof TriggersEditorIndexRoute
  '/workflows/editor/': typeof WorkflowsEditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/chat': typeof ChatRoute
  '/chat-debug': typeof ChatDebugRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/notifications': typeof NotificationsRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
  '/api/chat': typeof ApiChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/error-display': typeof DemoErrorDisplayRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/o/$': typeof OSplatRoute
  '/p/$pluginId': typeof PPluginIdRouteWithChildren
  '/requirements/$': typeof RequirementsSplatRoute
  '/settings/calendar': typeof SettingsCalendarRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/obsidian': typeof SettingsObsidianRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tasks/$': typeof TasksSplatRoute
  '/triggers/$': typeof TriggersSplatRoute
  '/workflows/$': typeof WorkflowsSplatRoute
  '/o': typeof OIndexRoute
  '/requirements': typeof RequirementsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/triggers': typeof TriggersIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/p/$pluginId/$pageId': typeof PPluginIdPageIdRoute
  '/settings/plugins/$pluginId': typeof SettingsPluginsPluginIdRoute
  '/tasks/editor/$': typeof TasksEditorSplatRoute
  '/triggers/editor/$': typeof TriggersEditorSplatRoute
  '/workflows/editor/$': typeof WorkflowsEditorSplatRoute
  '/settings/plugins': typeof SettingsPluginsIndexRoute
  '/tasks/editor': typeof TasksEditorIndexRoute
  '/triggers/editor': typeof TriggersEditorIndexRoute
  '/workflows/editor': typeof WorkflowsEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/chat': typeof ChatRoute
  '/chat-debug': typeof ChatDebugRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/notifications': typeof NotificationsRoute
  '/usage': typeof UsageRoute
  '/users': typeof UsersRoute
  '/api/chat': typeof ApiChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/error-display': typeof DemoErrorDisplayRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/o/$': typeof OSplatRoute
  '/p/$pluginId': typeof PPluginIdRouteWithChildren
  '/requirements/$': typeof RequirementsSplatRoute
  '/settings/calendar': typeof SettingsCalendarRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/obsidian': typeof SettingsObsidianRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/tasks/$': typeof TasksSplatRoute
  '/triggers/$': typeof TriggersSplatRoute
  '/workflows/$': typeof WorkflowsSplatRoute
  '/o/': typeof OIndexRoute
  '/requirements/': typeof RequirementsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/triggers/': typeof TriggersIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/p/$pluginId/$pageId': typeof PPluginIdPageIdRoute
  '/settings/plugins/$pluginId': typeof SettingsPluginsPluginIdRoute
  '/tasks/editor/$': typeof TasksEditorSplatRoute
  '/triggers/editor/$': typeof TriggersEditorSplatRoute
  '/workflows/editor/$': typeof WorkflowsEditorSplatRoute
  '/settings/plugins/': typeof SettingsPluginsIndexRoute
  '/tasks/editor/': typeof TasksEditorIndexRoute
  '/triggers/editor/': typeof TriggersEditorIndexRoute
  '/workflows/editor/': typeof WorkflowsEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/about'
    | '/activity'
    | '/chat'
    | '/chat-debug'
    | '/dashboard'
    | '/login'
    | '/logs'
    | '/notifications'
    | '/usage'
    | '/users'
    | '/api/chat'
    | '/demo/better-auth'
    | '/demo/error-display'
    | '/demo/prisma'
    | '/o/$'
    | '/p/$pluginId'
    | '/requirements/$'
    | '/settings/calendar'
    | '/settings/chat'
    | '/settings/notifications'
    | '/settings/obsidian'
    | '/settings/password'
    | '/settings/profile'
    | '/tasks/$'
    | '/triggers/$'
    | '/workflows/$'
    | '/o/'
    | '/requirements/'
    | '/settings/'
    | '/tasks/'
    | '/triggers/'
    | '/workflows/'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/p/$pluginId/$pageId'
    | '/settings/plugins/$pluginId'
    | '/tasks/editor/$'
    | '/triggers/editor/$'
    | '/workflows/editor/$'
    | '/settings/plugins/'
    | '/tasks/editor/'
    | '/triggers/editor/'
    | '/workflows/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/chat'
    | '/chat-debug'
    | '/dashboard'
    | '/login'
    | '/logs'
    | '/notifications'
    | '/usage'
    | '/users'
    | '/api/chat'
    | '/demo/better-auth'
    | '/demo/error-display'
    | '/demo/prisma'
    | '/o/$'
    | '/p/$pluginId'
    | '/requirements/$'
    | '/settings/calendar'
    | '/settings/chat'
    | '/settings/notifications'
    | '/settings/obsidian'
    | '/settings/password'
    | '/settings/profile'
    | '/tasks/$'
    | '/triggers/$'
    | '/workflows/$'
    | '/o'
    | '/requirements'
    | '/settings'
    | '/tasks'
    | '/triggers'
    | '/workflows'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/p/$pluginId/$pageId'
    | '/settings/plugins/$pluginId'
    | '/tasks/editor/$'
    | '/triggers/editor/$'
    | '/workflows/editor/$'
    | '/settings/plugins'
    | '/tasks/editor'
    | '/triggers/editor'
    | '/workflows/editor'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/about'
    | '/activity'
    | '/chat'
    | '/chat-debug'
    | '/dashboard'
    | '/login'
    | '/logs'
    | '/notifications'
    | '/usage'
    | '/users'
    | '/api/chat'
    | '/demo/better-auth'
    | '/demo/error-display'
    | '/demo/prisma'
    | '/o/$'
    | '/p/$pluginId'
    | '/requirements/$'
    | '/settings/calendar'
    | '/settings/chat'
    | '/settings/notifications'
    | '/settings/obsidian'
    | '/settings/password'
    | '/settings/profile'
    | '/tasks/$'
    | '/triggers/$'
    | '/workflows/$'
    | '/o/'
    | '/requirements/'
    | '/settings/'
    | '/tasks/'
    | '/triggers/'
    | '/workflows/'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/p/$pluginId/$pageId'
    | '/settings/plugins/$pluginId'
    | '/tasks/editor/$'
    | '/triggers/editor/$'
    | '/workflows/editor/$'
    | '/settings/plugins/'
    | '/tasks/editor/'
    | '/triggers/editor/'
    | '/workflows/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  ChatRoute: typeof ChatRoute
  ChatDebugRoute: typeof ChatDebugRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  NotificationsRoute: typeof NotificationsRoute
  UsageRoute: typeof UsageRoute
  UsersRoute: typeof UsersRoute
  ApiChatRoute: typeof ApiChatRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoErrorDisplayRoute: typeof DemoErrorDisplayRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  OSplatRoute: typeof OSplatRoute
  PPluginIdRoute: typeof PPluginIdRouteWithChildren
  RequirementsSplatRoute: typeof RequirementsSplatRoute
  TasksSplatRoute: typeof TasksSplatRoute
  TriggersSplatRoute: typeof TriggersSplatRoute
  WorkflowsSplatRoute: typeof WorkflowsSplatRoute
  OIndexRoute: typeof OIndexRoute
  RequirementsIndexRoute: typeof RequirementsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TriggersIndexRoute: typeof TriggersIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  TasksEditorSplatRoute: typeof TasksEditorSplatRoute
  TriggersEditorSplatRoute: typeof TriggersEditorSplatRoute
  WorkflowsEditorSplatRoute: typeof WorkflowsEditorSplatRoute
  TasksEditorIndexRoute: typeof TasksEditorIndexRoute
  TriggersEditorIndexRoute: typeof TriggersEditorIndexRoute
  WorkflowsEditorIndexRoute: typeof WorkflowsEditorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-debug': {
      id: '/chat-debug'
      path: '/chat-debug'
      fullPath: '/chat-debug'
      preLoaderRoute: typeof ChatDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triggers/': {
      id: '/triggers/'
      path: '/triggers'
      fullPath: '/triggers/'
      preLoaderRoute: typeof TriggersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/requirements/': {
      id: '/requirements/'
      path: '/requirements'
      fullPath: '/requirements/'
      preLoaderRoute: typeof RequirementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/': {
      id: '/o/'
      path: '/o'
      fullPath: '/o/'
      preLoaderRoute: typeof OIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$': {
      id: '/workflows/$'
      path: '/workflows/$'
      fullPath: '/workflows/$'
      preLoaderRoute: typeof WorkflowsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triggers/$': {
      id: '/triggers/$'
      path: '/triggers/$'
      fullPath: '/triggers/$'
      preLoaderRoute: typeof TriggersSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$': {
      id: '/tasks/$'
      path: '/tasks/$'
      fullPath: '/tasks/$'
      preLoaderRoute: typeof TasksSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/password': {
      id: '/settings/password'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof SettingsPasswordRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/obsidian': {
      id: '/settings/obsidian'
      path: '/obsidian'
      fullPath: '/settings/obsidian'
      preLoaderRoute: typeof SettingsObsidianRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/chat': {
      id: '/settings/chat'
      path: '/chat'
      fullPath: '/settings/chat'
      preLoaderRoute: typeof SettingsChatRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/calendar': {
      id: '/settings/calendar'
      path: '/calendar'
      fullPath: '/settings/calendar'
      preLoaderRoute: typeof SettingsCalendarRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/requirements/$': {
      id: '/requirements/$'
      path: '/requirements/$'
      fullPath: '/requirements/$'
      preLoaderRoute: typeof RequirementsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$pluginId': {
      id: '/p/$pluginId'
      path: '/p/$pluginId'
      fullPath: '/p/$pluginId'
      preLoaderRoute: typeof PPluginIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$': {
      id: '/o/$'
      path: '/o/$'
      fullPath: '/o/$'
      preLoaderRoute: typeof OSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/error-display': {
      id: '/demo/error-display'
      path: '/demo/error-display'
      fullPath: '/demo/error-display'
      preLoaderRoute: typeof DemoErrorDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/editor/': {
      id: '/workflows/editor/'
      path: '/workflows/editor'
      fullPath: '/workflows/editor/'
      preLoaderRoute: typeof WorkflowsEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triggers/editor/': {
      id: '/triggers/editor/'
      path: '/triggers/editor'
      fullPath: '/triggers/editor/'
      preLoaderRoute: typeof TriggersEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/editor/': {
      id: '/tasks/editor/'
      path: '/tasks/editor'
      fullPath: '/tasks/editor/'
      preLoaderRoute: typeof TasksEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/plugins/': {
      id: '/settings/plugins/'
      path: '/plugins'
      fullPath: '/settings/plugins/'
      preLoaderRoute: typeof SettingsPluginsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/workflows/editor/$': {
      id: '/workflows/editor/$'
      path: '/workflows/editor/$'
      fullPath: '/workflows/editor/$'
      preLoaderRoute: typeof WorkflowsEditorSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triggers/editor/$': {
      id: '/triggers/editor/$'
      path: '/triggers/editor/$'
      fullPath: '/triggers/editor/$'
      preLoaderRoute: typeof TriggersEditorSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/editor/$': {
      id: '/tasks/editor/$'
      path: '/tasks/editor/$'
      fullPath: '/tasks/editor/$'
      preLoaderRoute: typeof TasksEditorSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/plugins/$pluginId': {
      id: '/settings/plugins/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/settings/plugins/$pluginId'
      preLoaderRoute: typeof SettingsPluginsPluginIdRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/p/$pluginId/$pageId': {
      id: '/p/$pluginId/$pageId'
      path: '/$pageId'
      fullPath: '/p/$pluginId/$pageId'
      preLoaderRoute: typeof PPluginIdPageIdRouteImport
      parentRoute: typeof PPluginIdRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsCalendarRoute: typeof SettingsCalendarRoute
  SettingsChatRoute: typeof SettingsChatRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsObsidianRoute: typeof SettingsObsidianRoute
  SettingsPasswordRoute: typeof SettingsPasswordRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsPluginsPluginIdRoute: typeof SettingsPluginsPluginIdRoute
  SettingsPluginsIndexRoute: typeof SettingsPluginsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsCalendarRoute: SettingsCalendarRoute,
  SettingsChatRoute: SettingsChatRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsObsidianRoute: SettingsObsidianRoute,
  SettingsPasswordRoute: SettingsPasswordRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsPluginsPluginIdRoute: SettingsPluginsPluginIdRoute,
  SettingsPluginsIndexRoute: SettingsPluginsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface PPluginIdRouteChildren {
  PPluginIdPageIdRoute: typeof PPluginIdPageIdRoute
}

const PPluginIdRouteChildren: PPluginIdRouteChildren = {
  PPluginIdPageIdRoute: PPluginIdPageIdRoute,
}

const PPluginIdRouteWithChildren = PPluginIdRoute._addFileChildren(
  PPluginIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  ChatRoute: ChatRoute,
  ChatDebugRoute: ChatDebugRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  NotificationsRoute: NotificationsRoute,
  UsageRoute: UsageRoute,
  UsersRoute: UsersRoute,
  ApiChatRoute: ApiChatRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoErrorDisplayRoute: DemoErrorDisplayRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  OSplatRoute: OSplatRoute,
  PPluginIdRoute: PPluginIdRouteWithChildren,
  RequirementsSplatRoute: RequirementsSplatRoute,
  TasksSplatRoute: TasksSplatRoute,
  TriggersSplatRoute: TriggersSplatRoute,
  WorkflowsSplatRoute: WorkflowsSplatRoute,
  OIndexRoute: OIndexRoute,
  RequirementsIndexRoute: RequirementsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TriggersIndexRoute: TriggersIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  TasksEditorSplatRoute: TasksEditorSplatRoute,
  TriggersEditorSplatRoute: TriggersEditorSplatRoute,
  WorkflowsEditorSplatRoute: WorkflowsEditorSplatRoute,
  TasksEditorIndexRoute: TasksEditorIndexRoute,
  TriggersEditorIndexRoute: TriggersEditorIndexRoute,
  WorkflowsEditorIndexRoute: WorkflowsEditorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
